/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author cjordaney
 */
public class inicioCaja extends javax.swing.JFrame {

    /**
     * Creates new form inicioCaja
     */
    public inicioCaja() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    //public static Fondos fondoCaja;
    public static Float cajaPesos;
    public static Float cajaDolares;
    public static Float inicioCajaPesos;
    public static Float inicioCajaDolares;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inicioFondoPesos = new javax.swing.JTextField();
        inicioFondoDolares = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("PESOS");

        jLabel2.setText("DOLARES");

        inicioFondoPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioFondoPesosActionPerformed(evt);
            }
        });
        inicioFondoPesos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inicioFondoPesosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(35, 35, 35)
                            .addComponent(inicioFondoDolares))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(51, 51, 51)
                            .addComponent(inicioFondoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inicioFondoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inicioFondoDolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioFondoPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioFondoPesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioFondoPesosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*
        String fondoPesos = String.valueOf(jTextField1.getText());
        String fondoDolares = String.valueOf(jTextField2.getText());
        */
        
                    
        if(inicioFondoPesos.getText().isEmpty() || inicioFondoDolares.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Para iniciar debe ingresar Pesos y Dolares.", "Acceso denegado", 
                    JOptionPane.ERROR_MESSAGE);
        }
        else{
            //float fondoPesos = Float.parseFloat(String.valueOf(inicioFondoPesos.getText()));
            cajaPesos = Float.parseFloat(String.valueOf(inicioFondoPesos.getText()));
            inicioCajaPesos = cajaPesos;
            //float fondoDolares = Float.parseFloat(String.valueOf(inicioFondoDolares.getText()));
            cajaDolares = Float.parseFloat(String.valueOf(inicioFondoDolares.getText()));
            inicioCajaDolares = cajaDolares;
            
            //Fondos fondo = new Fondos();
            
            //fondoCaja.setPesos(fondoPesos);
            //fondoCaja.setDolares(fondoDolares);
            
            //System.out.println("Pesos: " + fondoPesos + " Dolares: " + fondoDolares );
            System.out.println("Pesos: " + cajaPesos + " Dolares: " + cajaDolares );
        
            tipoCambio ventana = new tipoCambio();
            ventana.setVisible(true);
            this.setVisible(false);    //this.dispose();
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inicioFondoPesosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicioFondoPesosKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        
        boolean numeros = key >= 48 && key <= 57;
        boolean punto = key == 46;
        
        if(!(numeros || punto)){
            evt.consume();
        }
    }//GEN-LAST:event_inicioFondoPesosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inicioFondoDolares;
    private javax.swing.JTextField inicioFondoPesos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
