/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author cjordaney
 */
public class operaciones extends javax.swing.JFrame {

    /**
     * Creates new form operaciones
     */
    public operaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        cotizacionCompra.setText(Float.toString(tipoCambio.valorCompra));
        cotizacionVenta.setText(Float.toString(tipoCambio.valorVenta));
        cajaPesos.setText(String.valueOf(inicioCaja.cajaPesos));
        cajaDolares.setText(String.valueOf(inicioCaja.cajaDolares));
        
    }

    //public static Fondos fondoOperacion;
    //public static Cambio cambioOpeacion;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonFijarTipoCambio = new javax.swing.JButton();
        botonCompra = new javax.swing.JButton();
        botonVenta = new javax.swing.JButton();
        botonCerrarCaja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cotizacionCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cotizacionVenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaPesos = new javax.swing.JTextField();
        cajaDolares = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonFijarTipoCambio.setText("Fijar Tipo Cambio");
        botonFijarTipoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFijarTipoCambioActionPerformed(evt);
            }
        });

        botonCompra.setText("Compra");
        botonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompraActionPerformed(evt);
            }
        });

        botonVenta.setText("Venta");
        botonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentaActionPerformed(evt);
            }
        });

        botonCerrarCaja.setText("Cerrar Caja");
        botonCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarCajaActionPerformed(evt);
            }
        });

        jLabel1.setText("Cotización");

        jLabel2.setText("Compra");

        cotizacionCompra.setEditable(false);
        cotizacionCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotizacionCompraActionPerformed(evt);
            }
        });

        jLabel3.setText("Venta");

        cotizacionVenta.setEditable(false);
        cotizacionVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotizacionVentaActionPerformed(evt);
            }
        });

        jLabel4.setText("Caja");

        jLabel5.setText("Pesos");

        jLabel6.setText("Dólares");

        cajaPesos.setEditable(false);
        cajaPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPesosActionPerformed(evt);
            }
        });

        cajaDolares.setEditable(false);
        cajaDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDolaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cotizacionCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cotizacionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaDolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFijarTipoCambio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(botonFijarTipoCambio)
                .addGap(18, 18, 18)
                .addComponent(botonCompra)
                .addGap(18, 18, 18)
                .addComponent(botonVenta)
                .addGap(18, 18, 18)
                .addComponent(botonCerrarCaja)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cotizacionCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cajaPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotizacionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(cajaDolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFijarTipoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFijarTipoCambioActionPerformed
        // TODO add your handling code here:
        tipoCambio ventana = new tipoCambio();
            ventana.setVisible(true);
            this.setVisible(false);  
    }//GEN-LAST:event_botonFijarTipoCambioActionPerformed

    private void botonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompraActionPerformed
        // TODO add your handling code here:
        //if(inicioCaja.fondo.getPesos() == 0f){
        if(inicioCaja.cajaPesos == 0f){
            JOptionPane.showMessageDialog(null,"No tiene pesos para comprar dólares", "Acceso denegado", 
                    JOptionPane.ERROR_MESSAGE);
        }
        else{
            compra ventana = new compra();
            ventana.setVisible(true);
            this.setVisible(false);  
        }
    }//GEN-LAST:event_botonCompraActionPerformed

    private void cotizacionCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotizacionCompraActionPerformed
        // TODO add your handling code here:
        //cotizacionCompra.setText(tipoCambio.cambio.getCompra());
        cotizacionCompra.setText(Float.toString(tipoCambio.valorCompra));
    }//GEN-LAST:event_cotizacionCompraActionPerformed

    private void cotizacionVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotizacionVentaActionPerformed
        // TODO add your handling code here:
        //cotizacionVenta.setText(tipoCambio.cambio.getVenta());
        cotizacionVenta.setText(Float.toString(tipoCambio.valorVenta));
    }//GEN-LAST:event_cotizacionVentaActionPerformed

    private void cajaPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPesosActionPerformed
        // TODO add your handling code here:
        //cajaPesos.setText(String.valueOf(inicioCaja.fondo.getPesos()));
        cajaPesos.setText(String.valueOf(inicioCaja.cajaPesos));
    }//GEN-LAST:event_cajaPesosActionPerformed

    private void cajaDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDolaresActionPerformed
        // TODO add your handling code here:
        //cajaDolares.setText(String.valueOf(inicioCaja.fondo.getDolares()));
        cajaDolares.setText(String.valueOf(inicioCaja.cajaDolares));
    }//GEN-LAST:event_cajaDolaresActionPerformed

    private void botonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentaActionPerformed
        // TODO add your handling code here:
        //if(inicioCaja.fondo.getDolares() == 0f){
        if(inicioCaja.cajaDolares == 0f){
            JOptionPane.showMessageDialog(null,"No tiene dólares para vender", "Acceso denegado", 
                    JOptionPane.ERROR_MESSAGE);
        }
        else{
            venta ventana = new venta();
            ventana.setVisible(true);
            this.setVisible(false);  
            
        }
    }//GEN-LAST:event_botonVentaActionPerformed

    private void botonCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarCajaActionPerformed
        // TODO add your handling code here:
            cierreCaja ventana = new cierreCaja();
            ventana.setVisible(true);
            this.setVisible(false);  
    }//GEN-LAST:event_botonCerrarCajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarCaja;
    private javax.swing.JButton botonCompra;
    private javax.swing.JButton botonFijarTipoCambio;
    private javax.swing.JButton botonVenta;
    private javax.swing.JTextField cajaDolares;
    private javax.swing.JTextField cajaPesos;
    private javax.swing.JTextField cotizacionCompra;
    private javax.swing.JTextField cotizacionVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
